### ISSUE TITLE
Pocketmine 

### ISSUE THREAD

**Issue by GabBiswajit** [Trollhunters501/Barrel-CREA-Edition#1]
Support pocketmine??

**Comment by Trollhunters501** [comment]
Only as a proxy apart from the server altogether only nukkit

**Comment by Trollhunters501** [comment]
Plz in https://github.com/Trollhunters501/Barrel-CREA-Edition/discussions

**Comment by RealMucus** [comment]
theres a bug where when you leave the server you gain back the hearts you lost on top of the default hearts

**Comment by Trollhunters501** [comment]
If the next update would be fixed
